# Generated by Django 4.2.13 on 2026-09-16 14:49

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Payment'), ('active', 'Active'), ('used', 'Used'), ('expired', 'Expired')], default='pending', max_length=10)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('mac_address', models.CharField(blank=True, max_length=17)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VoucherPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('duration_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('data_mb', models.PositiveIntegerField(blank=True, null=True)),
                ('price_kes', models.DecimalField(decimal_places=2, max_digits=8)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['price_kes'],
            },
        ),
        migrations.CreateModel(
            name='WifiSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nas_ip', models.GenericIPAddressField()),
                ('client_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('mac_address', models.CharField(max_length=17)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('bytes_in', models.BigIntegerField(default=0)),
                ('bytes_out', models.BigIntegerField(default=0)),
                ('voucher', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='session', to='portal.voucher')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.AddField(
            model_name='voucher',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vouchers', to='portal.voucherplan'),
        ),
    ]
