# Generated by Django 4.2.13 on 2026-09-24 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_bandwidthsnapshot_hypertable'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('condition', models.CharField(choices=[('device_down', 'Device Down'), ('device_up', 'Device Up (recovery)'), ('high_bandwidth', 'High Bandwidth Usage')], max_length=20)),
                ('threshold_mbps', models.PositiveIntegerField(blank=True, help_text='For high_bandwidth: alert when Mbps exceeds this value', null=True)),
                ('notify_email', models.EmailField(help_text='Email address to notify when this rule fires', max_length=254)),
                ('cooldown_minutes', models.PositiveIntegerField(default=30, help_text='Minimum minutes between repeated alerts for the same device')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alert_rules', to='network.device')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AlertEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('fired_at', models.DateTimeField(auto_now_add=True)),
                ('email_sent', models.BooleanField(default=False)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_events', to='network.device')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='network.alertrule')),
            ],
            options={
                'ordering': ['-fired_at'],
            },
        ),
    ]
