# Generated by Django 4.2.13 on 2026-09-16 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RadiusNas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nasname', models.CharField(max_length=128, unique=True)),
                ('shortname', models.CharField(blank=True, max_length=32)),
                ('type', models.CharField(default='other', max_length=30)),
                ('ports', models.IntegerField(blank=True, null=True)),
                ('secret', models.CharField(max_length=60)),
                ('server', models.CharField(blank=True, max_length=64)),
                ('community', models.CharField(blank=True, max_length=50)),
                ('description', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'verbose_name': 'NAS',
                'verbose_name_plural': 'NAS Devices',
                'db_table': 'nas',
            },
        ),
        migrations.CreateModel(
            name='RadiusUserGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=64)),
                ('groupname', models.CharField(max_length=64)),
                ('priority', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'radusergroup',
                'unique_together': {('username', 'groupname')},
            },
        ),
    ]
